<?php
// @TODO: A str_replace is done in Media.tpl.php to remove autoplay from the embed code.
// The video shown on a mediahub video page and the embed code are generated by the same instance of
// UNL_MediaHub_Media so the check below is insufficient for removing autoplay from embed code.
$autoplay = 'autoplay';
if ($parent->context instanceof UNL_MediaHub_Media_Preview) {
    $autoplay = '';
}
?>
<video class="wdn_player" style="width:100%;height:100%" <?php echo $autoplay; ?> src="<?php echo $context->url?>" controls poster="<?php echo $context->getThumbnailURL(); ?>">
    <track src="<?php echo $context->getVideoTextTrackURL(); ?>" kind="subtitles" srclang="en" />
</video>
